import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'About',
  description: 'About Araverus — AI-powered financial news intelligence platform.',
};

export default function AboutPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16 text-gray-800 dark:text-gray-200">
      <h1 className="mb-8 text-3xl font-bold">About Araverus</h1>

      <section className="space-y-6 leading-relaxed">
        <p>
          The name <em>Araverus</em> comes from Latin:{' '}
          <strong>Ara</strong> (altar, sanctuary) and <strong>Verus</strong> (true, genuine)
          — <em>the Altar of Truth</em>. In an era of information overload, noise, and
          misinformation, Araverus is built to be a sanctuary where financial news is distilled
          to what is true and what matters.
        </p>

        <p>
          Araverus is a financial news intelligence platform that leverages artificial intelligence
          to deliver curated, concise, and actionable market insights.
        </p>

        <div>
          <h2 className="mb-2 text-xl font-semibold">Our Mission</h2>
          <p>
            Financial news is fragmented and overwhelming. Araverus exists to cut through the noise
            — providing clear, AI-powered intelligence so you can stay informed without the
            information overload.
          </p>
        </div>

        <div>
          <h2 className="mb-2 text-xl font-semibold">How It Works</h2>
          <p>
            Our system accumulates financial news from hundreds of trusted sources, updated in
            daily batches. Using machine learning and neural network-based vector embedding 
            similarity scoring, articles are clustered into coherent story threads and scored 
            for relevance. Each thread then passes through multi-agent validation pipelines 
            before generating original briefings. The result is a streamlined daily digest: 
            not aggregated headlines, but synthesized intelligence written from multiple sources.
          </p>
        </div>

        <div>
          <h2 className="mb-2 text-xl font-semibold">AI Transparency</h2>
          <p>
            We believe in full transparency about our use of AI. The briefings, summaries, and
            analyses on Araverus are generated by large language models with multi-stage quality
            checks and human oversight. Despite our rigorous validation pipeline, AI-generated
            content may occasionally contain inaccuracies. We encourage readers to verify critical
            information through primary sources.
          </p>
        </div>

        <div>
          <h2 className="mb-2 text-xl font-semibold">Our Symbol</h2>
          <p>
            The Araverus logo draws inspiration from the <em>monad</em> — a circumpunct, or a
            dot within a circle. In philosophy and mathematics, the monad represents unity, the
            origin, and an indivisible source of truth. We adopted this ancient symbol because it
            mirrors what we do: distilling a universe of fragmented financial data into a single
            point of clarity.
          </p>
        </div>
      </section>
    </main>
  );
}
