#!/bin/bash

# Script to set up Vercel environment variables
# Usage: ./scripts/setup-vercel-env.sh

echo "🚀 Vercel Environment Variables Setup"
echo "====================================="
echo ""
echo "This script will help you configure environment variables in Vercel."
echo ""
echo "📋 Required Variables for ALL environments:"
echo "-------------------------------------------"
echo "NEXT_PUBLIC_SUPABASE_URL"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "SUPABASE_SERVICE_ROLE_KEY"
echo ""
echo "📋 Environment-specific variables:"
echo "-----------------------------------"
echo "For Preview & Development:"
echo "  - Use your development Supabase project credentials"
echo "  - No NEXT_PUBLIC_BASE_URL needed (auto-detected)"
echo ""
echo "For Production:"
echo "  - Use production Supabase project credentials"
echo "  - NEXT_PUBLIC_BASE_URL=https://chopaul.com"
echo ""
echo "🔧 Steps to configure in Vercel Dashboard:"
echo "-------------------------------------------"
echo "1. Go to: https://vercel.com/[your-team]/araverus/settings/environment-variables"
echo "2. Add each variable with these settings:"
echo ""
echo "   For DEVELOPMENT variables:"
echo "   - Key: [VARIABLE_NAME]"
echo "   - Value: [from .env.development]"
echo "   - Environment: ✓ Preview ✓ Development"
echo ""
echo "   For PRODUCTION variables:"
echo "   - Key: [VARIABLE_NAME]"
echo "   - Value: [from .env.production when ready]"
echo "   - Environment: ✓ Production"
echo ""
echo "📝 Current .env.development values to add:"
echo "-------------------------------------------"
if [ -f .env.development ]; then
    echo ""
    grep -E "^(NEXT_PUBLIC_|SUPABASE_)" .env.development | sed 's/=.*/=<hidden>/'
else
    echo "⚠️  .env.development not found"
fi
echo ""
echo "🔐 Security Notes:"
echo "------------------"
echo "- NEVER commit .env.local or .env.production with real keys"
echo "- SERVICE_ROLE_KEY should only be in Production environment"
echo "- Use different Supabase projects for dev and prod"
echo ""
echo "Ready to configure? Visit your Vercel dashboard now!"
echo "https://vercel.com/dashboard"